/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp5;

import java.util.HashMap;
import java.util.TreeSet;

/**
 *
 * @author Ryzen3
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName());

    public static HashMap<Long, Cliente> directorio = new HashMap<>();
    public static TreeSet<String> ciudades = new TreeSet<>();

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Cliente = new javax.swing.JMenu();
        jMenuItem1agregarCliente = new javax.swing.JMenuItem();
        jMenuItem2buscaCliente = new javax.swing.JMenuItem();
        jMenuItem3borrarCliente = new javax.swing.JMenuItem();
        jMenu2Directorio = new javax.swing.JMenu();
        jMenuItem4busquedaxCiudad = new javax.swing.JMenuItem();
        jMenuItem5telefonoxapellido = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1agregarCiudad = new javax.swing.JMenuItem();
        jMenu6salir = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        jMenu1Cliente.setText("Clientes");

        jMenuItem1agregarCliente.setText("Agregar cliente");
        jMenuItem1agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1agregarClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItem1agregarCliente);

        jMenuItem2buscaCliente.setText("Buscar cliente");
        jMenuItem2buscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2buscaClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItem2buscaCliente);

        jMenuItem3borrarCliente.setText("Borrar cliente");
        jMenuItem3borrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3borrarClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItem3borrarCliente);

        jMenuBar1.add(jMenu1Cliente);

        jMenu2Directorio.setText("Directorio");

        jMenuItem4busquedaxCiudad.setText("Buscar clientes por ciudad");
        jMenuItem4busquedaxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4busquedaxCiudadActionPerformed(evt);
            }
        });
        jMenu2Directorio.add(jMenuItem4busquedaxCiudad);

        jMenuItem5telefonoxapellido.setText("Buscar telefono por apellido");
        jMenuItem5telefonoxapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5telefonoxapellidoActionPerformed(evt);
            }
        });
        jMenu2Directorio.add(jMenuItem5telefonoxapellido);

        jMenuBar1.add(jMenu2Directorio);

        jMenu4.setText("Ciudades");

        jMenuItem1agregarCiudad.setText("Agregar ciudad");
        jMenuItem1agregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1agregarCiudadActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1agregarCiudad);

        jMenuBar1.add(jMenu4);

        jMenu6salir.setText("Salir");
        jMenu6salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6salirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1agregarClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Clientes clientes = new Clientes();
        clientes.setVisible(true);
        jDesktopPane1.add(clientes);
        jDesktopPane1.moveToFront(clientes);
    }//GEN-LAST:event_jMenuItem1agregarClienteActionPerformed

    private void jMenuItem2buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2buscaClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        BucarClientes buscar = new BucarClientes();
        buscar.setVisible(true);
        jDesktopPane1.add(buscar);
        jDesktopPane1.moveToFront(buscar);
    }//GEN-LAST:event_jMenuItem2buscaClienteActionPerformed

    private void jMenuItem3borrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3borrarClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmBorrar borrar = new FrmBorrar();
        borrar.setVisible(true);
        jDesktopPane1.add(borrar);
        jDesktopPane1.moveToFront(borrar);
    }//GEN-LAST:event_jMenuItem3borrarClienteActionPerformed

    private void jMenuItem4busquedaxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4busquedaxCiudadActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        FrmBuscarClienteCiudad buscarCiudad = new FrmBuscarClienteCiudad();
        buscarCiudad.setVisible(true);
        jDesktopPane1.add(buscarCiudad);
        jDesktopPane1.moveToFront(buscarCiudad);
    }//GEN-LAST:event_jMenuItem4busquedaxCiudadActionPerformed

    private void jMenuItem5telefonoxapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5telefonoxapellidoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Frm_BuscarTelefonoPorApellido buscarApellido = new Frm_BuscarTelefonoPorApellido();
        buscarApellido.setVisible(true);
        jDesktopPane1.add(buscarApellido);
        jDesktopPane1.moveToFront(buscarApellido);
    }//GEN-LAST:event_jMenuItem5telefonoxapellidoActionPerformed

    private void jMenu6salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu6salirActionPerformed

    private void jMenuItem1agregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1agregarCiudadActionPerformed
    jDesktopPane1.removeAll();
    jDesktopPane1.repaint();
    Ciudades agregarCiudad = new Ciudades();
    agregarCiudad.setVisible(true);
    jDesktopPane1.add(agregarCiudad);
    jDesktopPane1.moveToFront(agregarCiudad);    }//GEN-LAST:event_jMenuItem1agregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1Cliente;
    private javax.swing.JMenu jMenu2Directorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6salir;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1agregarCiudad;
    private javax.swing.JMenuItem jMenuItem1agregarCliente;
    private javax.swing.JMenuItem jMenuItem2buscaCliente;
    private javax.swing.JMenuItem jMenuItem3borrarCliente;
    private javax.swing.JMenuItem jMenuItem4busquedaxCiudad;
    private javax.swing.JMenuItem jMenuItem5telefonoxapellido;
    // End of variables declaration//GEN-END:variables
}
